package com.mavenir.entity;

// Generated 5 Jun, 2008 11:22:52 AM by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;





/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "releaseList", catalog = "mTool" )
public class Release implements java.io.Serializable {

	private String productName;
	private Integer oidIndex;
	private String name; 
	private String status; 
	private String owner; 
	private Date startDate; 
	private Date endDate; 
	private String mnodeAvailable; 
	
	




	private String comments; 



	
	
	public Release() {
	}


	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "oid_index", unique = true, nullable = false)
	public Integer getOidIndex() {
		return this.oidIndex;
	}

	public void setOidIndex(Integer oidIndex) {
		this.oidIndex = oidIndex;
	}
	
	
	
	@Column(name = "releaseName", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}



	@Column(name = "productName", length = 100)
	public String getProductName() {
		return productName;
	}




	public void setProductName(String productName) {
		this.productName = productName;
	}



	@Column(name = "status", length = 100)
	public String getStatus() {
		return status;
	}




	public void setStatus(String status) {
		this.status = status;
	}



	@Column(name = "owner", length = 100)
	public String getOwner() {
		return owner;
	}




	public void setOwner(String owner) {
		this.owner = owner;
	}



	@Column(name = "startDate")
	public Date getStartDate() {
		return startDate;
	}




	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}



	@Column(name = "endDate")
	public Date getEndDate() {
		return endDate;
	}




	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}



	@Column(name = "mnodeAvailable", length = 100)
	public String getMnodeAvailable() {
		return mnodeAvailable;
	}




	public void setMnodeAvailable(String mnodeAvailable) {
		this.mnodeAvailable = mnodeAvailable;
	}



	@Column(name = "comments", length = 100)
	public String getComments() {
		return comments;
	}




	public void setComments(String comments) {
		this.comments = comments;
	}

	

}
